List<Map<String, String>> details = [
  {
    "name": "Mini Cooper",
    "bio": "Sportcar",
    "image": "assets/images/car1.jpg",
    "likes": "110",
    "comments": "20",
    "published day": "1",
  },
  {
    "type": "1",
  },
  {
    "name": "Rolls Royce",
    "bio": "Luxurycar",
    "image": "assets/images/car2.webp",
    "likes": "210",
    "comments": "40",
    "published day": "2",
  },
  {
    "name": "Range Rover",
    "bio": "Sportcar,LuxuryCar",
    "image": "assets/images/car3.webp",
    "likes": "310",
    "comments": "60",
    "published day": "3",
  },
  {
    "name": "Bugati",
    "bio": "Sportcar",
    "image": "assets/images/car4.webp",
    "likes": "410",
    "comments": "80",
    "published day": "4",
  },
  {
    "name": "Ferrai",
    "bio": "Sportcar",
    "image": "assets/images/car5.jpg",
    "likes": "510",
    "comments": "100",
    "published day": "5",
  },
  {
    "name": "BMW",
    "bio": "Sportcar,Luxurycar",
    "image": "assets/images/car6.webp",
    "likes": "610",
    "comments": "120",
    "published day": "6",
  },
  {
    "name": "Ferrai",
    "bio": "Sportcar",
    "image": "assets/images/car7.jpg",
    "likes": "710",
    "comments": "140",
    "published day": "7",
  },
  {
    "name": "Mercedes",
    "bio": "Lucurycar",
    "image": "assets/images/car8.jpg",
    "likes": "810",
    "comments": "160",
    "published day": "8",
  },
  {
    "name": "BMW",
    "bio": "Sportcar,Luxurycar",
    "image": "assets/images/car9.jpg",
    "likes": "910",
    "comments": "180",
    "published day": "9",
  },
  {
    "name": "Ferrai",
    "bio": "Sportcar",
    "image": "assets/images/car10.jpg",
    "likes": "1010",
    "comments": "200",
    "published day": "10",
  },
];
List<Map<String, String>> messageList = [
  {
    "name": "Mini Cooper",
    "bio": "Sportcar",
    "image": "assets/images/car1.jpg",
    "likes": "110",
    "comments": "20",
    "published day": "1",
  },
  {
    "name": "Rolls Royce",
    "bio": "Luxurycar",
    "image": "assets/images/car2.webp",
    "likes": "210",
    "comments": "40",
    "published day": "2",
  },
  {
    "name": "Range Rover",
    "bio": "Sportcar,LuxuryCar",
    "image": "assets/images/car3.webp",
    "likes": "310",
    "comments": "60",
    "published day": "3",
  },
  {
    "name": "Bugati",
    "bio": "Sportcar",
    "image": "assets/images/car4.webp",
    "likes": "410",
    "comments": "80",
    "published day": "4",
  },
  {
    "name": "Ferrai",
    "bio": "Sportcar",
    "image": "assets/images/car5.jpg",
    "likes": "510",
    "comments": "100",
    "published day": "5",
  },
  {
    "name": "BMW",
    "bio": "Sportcar,Luxurycar",
    "image": "assets/images/car6.webp",
    "likes": "610",
    "comments": "120",
    "published day": "6",
  },
  {
    "name": "Ferrai",
    "bio": "Sportcar",
    "image": "assets/images/car7.jpg",
    "likes": "710",
    "comments": "140",
    "published day": "7",
  },
  {
    "name": "Mercedes",
    "bio": "Lucurycar",
    "image": "assets/images/car8.jpg",
    "likes": "810",
    "comments": "160",
    "published day": "8",
  },
  {
    "name": "BMW",
    "bio": "Sportcar,Luxurycar",
    "image": "assets/images/car9.jpg",
    "likes": "910",
    "comments": "180",
    "published day": "9",
  },
  {
    "name": "Ferrai",
    "bio": "Sportcar",
    "image": "assets/images/car10.jpg",
    "likes": "1010",
    "comments": "200",
    "published day": "10",
  },
];
List<Map<String, String>> videoList = [
  {
    "name": "Mini Cooper",
    "bio": "#sad",
    "video": "assets/videos/1.mp4",
    "image": "assets/images/car1.jpg",
    "likes": "110",
    "comments": "20",
    "share": "100",
  },
  {
    "name": "Rolls Royce",
    "bio": "#sad",
    "video": "assets/videos/2.mp4",
    "image": "assets/images/car2.webp",
    "likes": "210",
    "comments": "40",
    "share": "200",
  },
  {
    "name": "Range Rover",
    "bio": "#love",
    "video": "assets/videos/3.mp4",
    "image": "assets/images/car3.webp",
    "likes": "310",
    "comments": "60",
    "share": "300",
  },
  {
    "name": "Bugati",
    "bio": "#love",
    "video": "assets/videos/4.mp4",
    "image": "assets/images/car4.webp",
    "likes": "410",
    "comments": "80",
    "share": "400",
  },
  {
    "name": "Ferrai",
    "bio": "#comedy",
    "video": "assets/videos/5.mp4",
    "image": "assets/images/car5.jpg",
    "likes": "510",
    "comments": "100",
    "share": "500",
  },
  {
    "name": "BMW",
    "bio": "#comedy",
    "video": "assets/videos/6.mp4",
    "image": "assets/images/car6.webp",
    "likes": "610",
    "comments": "120",
    "share": "600",
  },
  {
    "name": "Ferrai",
    "bio": "#trending",
    "video": "assets/videos/7.mp4",
    "image": "assets/images/car7.jpg",
    "likes": "710",
    "comments": "140",
    "share": "700",
  },
  {
    "name": "Mercedes",
    "bio": "#trending",
    "video": "assets/videos/8.mp4",
    "image": "assets/images/car8.jpg",
    "likes": "810",
    "comments": "160",
    "share": "800",
  }
];
